config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show] do
    # 自製的連結，因為不符合 RESTful 的七個名稱，所以要標注動詞(post)、使用的路徑名稱、對象是單一(member)還是全部
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
  end
  root 'products#index'

  resource :cart
  # 因為 cart 上的商品加減都會用到，所以全開

  resources :orders do
    post :checkout_spgateway, on: :member
    # post :spgateway_return, on: :collection
    # 打算繞過 orders，改採下方寫法
  end

  post "spgateway/return" #因此需要專屬的 controller
  post "spgateway/notify"

  namespace :admin do
    resources :products
    resources :users
    resources :orders
    root 'products#index'
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates_presence_of :name, :address, :phone, :payment_status, :shipping_status

  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  has_many :payments, dependent: :destroy

  belongs_to :user

  PAYMENT_STATUS = [
    ["Not Paid", :not_paid],
    ["Paid", :paid]
  ]

  SHIPPING_STATUS = [
    ["Not Shipped", :not_shipped],
    ["Shipped", :shipped]
  ]

  def add_order_items(cart)
    cart.cart_items.each do |item|
      self.order_items.build(
        product_id: item.product.id,
        quantity: item.quantity,
        price: item.product.price
      )
    end
  end

  def subtotal
    order_items.map{ |x| x.item_total }.sum
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::AdminController
  def index
    @orders = Order.order(created_at: :desc)
  end

  def edit
    @order = Order.find(params[:id])
  end
  
  def update
    @order = Order.find(params[:id])
      if @order.update(order_params)
        if @order.shipping_status == "shipped"
          UserMailer.notify_order_shipped(@order).deliver_now
        end
        if @order.shipping_status == "paid"
          UserMailer.notify_order_paid(@order).deliver_now
        end
        redirect_to admin_orders_path, notice: "Order was successfully updated"
      else
        flash.now[:alert] = @order.errors.full_messages.to_sentence
        render "admin/orders/edit"
      end
  end

  private

  def order_params
    params.require(:order).permit(:payment_status, :shipping_status)
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
   
  def index
    @orders = current_user.orders.order(created_at: :desc)
  end

  def create
    # 手動確認是否登入
    if current_user.nil?
      # 如果 session 有檔案，便可以在之後取回
      session[:new_order_data] = params[:order]
      # 回到 devise 登入頁面
      redirect_to new_user_session_path
    else
      @order = current_user.orders.new(order_params)
      @order.sn = rand(100..999) + @order.id.to_i + Time.now.to_i
      @order.add_order_items(current_cart)
      @order.amount = current_cart.subtotal

      if @order.save
        current_cart.destroy
        # 訂單建立後，相關檔案要清除
        session.delete(:new_order_data)
        #UserMailer.notify_order_create(@order).deliver_now!
        redirect_to orders_path, notice: "now order created"
      else
        @items = current_cart.cart_items
        render "carts/show"
      end
    end

  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = current_user.orders.find(params[:id])
    if @order.shipping_status == "not_shipped"
      @order.shipping_status = "cancelled"
      @order.save
      redirect_to orders_path, alert: "order ##{@order.sn} cancelled"
    end
  end
  
  def checkout_spgateway
    @order = current_user.orders.find(params[:id])
    if @order.payment_status != "not_paid"
      flash[:alert] = "Order has been paid."
      redirect_to orders_path
    else
      @payment = Payment.create!(
        sn: Time.now.to_i,
        order_id: @order.id,
        payment_method: params[:payment_method],
        amount: @order.amount
      )

      # 關掉 application.html.erb
      render layout: false
    end
  end
    
  private

  def order_params
    params.require(:order).permit(:name, :phone, :payment_status, :address)
  end
  
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/edit.html.erb
<%= form_for [:admin, @order] do |f| %>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Order Detail</h1>
      <table class="table table-striped table-bordered">
        <caption style="text-align:center;">Product List</caption>
        <thead>
          <tr>
            <th colspan="3">
              Order # <%= @order.sn %>
            </th>
          </tr>
          <tr>
            <th>
              Product Name
            </th>
            <th>
              Product Quantity
            </th>
            <th>
              Product amount
            </th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_items.each do |item| %>
            <tr>
              <td>
                <%= item.product.name %>
              </td>
              <td>
                <%= item.quantity %>
              </td>
              <td>
                <%= item.price * item.quantity %>
              </td>
            </tr>
            <% end %>
              <tr>
                <td colspan="3" , style="text-align: center;">
                  <strong>Total Amount:
                    <%= @order.subtotal %>
                  </strong>
                </td>
              </tr>
        </tbody>
      </table>
      <hr>
      <table class="table table-striped table-bordered">
        <caption style="text-align:center;">Shipping Information</caption>
        <tr>
          <th>
            Name:
          </th>
          <td>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>
            Phone:
          </th>
          <td>
            <%= @order.phone %>
          </td>
        </tr>
        <tr>
          <th>
            Address:
          </th>
          <td>
            <%= @order.address %>
          </td>
        </tr>
      </table>
      <hr>
      <table class="table table-striped table-bordered">
        <caption style="text-align:center;">Payment Information</caption>
        <tr>
          <th>
            Payment Method:
          </th>
          <td>
            <%#= @order.payment_method %>
          </td>
        </tr>
        <tr>
          <th>
            Payment Status:
          </th>
          <td>
            <%= f.select :payment_status, Order::PAYMENT_STATUS %>
          </td>
        </tr>
        <tr>
          <th>
            Shipping Status:
          </th>
          <td>
            <%= f.select :shipping_status, Order::SHIPPING_STATUS %>
          </td>
        </tr>
        <tr>
          <td colspan="2" , style="text-align:center;">
            <%= f.submit %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<% end %>

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="switch">
        <ul class="admin-nav">
          <li class="btn btn-default">
            <%= link_to "Products", admin_products_path %>
          </li>
          <li class="btn btn-default active">
            <%= link_to "Orders", admin_orders_path %>
          </li>
          <li class="btn btn-default">
            <%= link_to "Users", admin_users_path %>
          </li>
        </ul>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>
              Order Number
            </th>
            <th>
              Customer
            </th>
            <th>
              Price
            </th>
            <th>
              Payment Status
            </th>
            <th>
              Shipping Status
            </th>
            <th>
              Option
            </th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= order.sn %></td>
            <td><%= order.user.email %></td>
            <td><%= order.amount %></td>
            <td><%= order.payment_status %></td>
            <td><%= order.shipping_status %></td>
            <td>
              <%= link_to "Edit Detail", edit_admin_order_path(order) %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>