config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show] do
    # 自製的連結，因為不符合 RESTful 的七個名稱，所以要標注動詞(post)、使用的路徑名稱、對象是單一(member)還是全部
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
  end
  root 'products#index'

  resource :cart
  # 因為 cart 上的商品加減都會用到，所以全開

  resources :orders do
    post :checkout_spgateway, on: :member
    # post :spgateway_return, on: :collection
    # 打算繞過 orders，改採下方寫法
  end

  post "spgateway/return" #因此需要專屬的 controller
  post "spgateway/notify"

  namespace :admin do
    resources :products
    resources :users
    resources :orders
    root 'products#index'
  end
end

app/views/shared/_cart.html.erb
<aside class="col-md-4">
  <h1>Cart</h1>
  <hr>
  <div class="item-list">
    <% current_cart.cart_items.each do |item| %>
    <%= render partial: "shared/item", locals: { item: item } %>
    <!-- 把 items 用 render 獨立出來 -->
    <!-- locals用來設定指定變數，在不同view下，指定的變數該用什麼變數，item: 表示指定的變數； item 表示要用什麼變數 -->
    <% end %>
  </div>
  <hr>
  <div class="subtotal">
    <p>SUBTOTAL</p>
    <p class="amount"><%= current_cart.subtotal %></p>
  </div>
  <%= link_to "View Cart", cart_path %>
</aside>

app/views/shared/_form_error.html.erb
<% if object.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_item.html.erb
<div class="cart-item product-<%= item.product.id %>">
  <img src="https://robohash.org/UNC.png?set=set1">
  <div class="cart-item-info">
    <h3><%= item.product.name %></h3>
    $ <%= item.product.price %>
    <div class="cart-item-adjust">
      <%= link_to "+", adjust_item_product_path(item.product, type: "add"), method: :post, remote: true %>
      <!-- 增加數量的按鈕，動詞是 post -->
      <span class="cart-<%= item.product.id %>-qty"><%= item.quantity %></span>
      <!-- 取得數量，這邊的設計巧思是 class -->
      <%= link_to "-", adjust_item_product_path(item.product, type: "substract"), method: :post, remote: true %>
      <!-- 減少數量的按鈕，動詞是 post -->
      <%= link_to "", remove_from_cart_product_path(item.product), method: :post, remote: true, class: "glyphicon glyphicon-trash" %>
      <!-- 全部刪除，動詞是 post -->
    </div>
  </div>
</div>