config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show] do
    # 自製的連結，因為不符合 RESTful 的七個名稱，所以要標注動詞(post)、使用的路徑名稱、對象是單一(member)還是全部
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
  end
  root 'products#index'

  resource :cart
  # 因為 cart 上的商品加減都會用到，所以全開

  resources :orders do
    post :checkout_spgateway, on: :member
    # post :spgateway_return, on: :collection
    # 打算繞過 orders，改採下方寫法
  end

  post "spgateway/return" #因此需要專屬的 controller
  post "spgateway/notify"

  namespace :admin do
    resources :products
    resources :users
    resources :orders
    root 'products#index'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :name, :description, :price
  # 驗證欄位，確保指定的屬性有填寫

  mount_uploader :image, PhotoUploader
  # carrierwave 的載具

  has_many :cart_items, dependent: :destroy
  has_many :carts, through: :cart_items
  # 因為連結關聯表，因此會有另一張間接的表，要標示出來(用through)

  has_many :order_items
  has_many :orders, through: :order_items
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :set_product, only: [:edit, :update, :show, :destory]
  def index
    @products = Product.page(params[:page]).per(10) # 撈資料，首頁顯示的數量
  end

  def new
    @product = Product.new # 物件的建立都要用 new
  end

  def create
    @product = Product.new(product_params) # 注意已經把「驗證」用private抽離
    if @product.save
      flash[:notice] = "Product successfully created"
      redirect_to admin_products_path
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end
  
  def update
    if @product.update_attributes(product_params) 
      # update_attributes 會接收傳進來的 Hash 並且 save，如果 object 無效或是被 validation 擋下的話會回傳 false
      flash[:notice] = "Product was successfully updated"
      redirect_to admin_product_path(@product)
    else
      flash[:alert] = "Something went wrong"
      render :edit
    end
  end
  
  def destroy
    if @product.destroy
      flash[:alert] = 'Product was successfully deleted.'
      redirect_to admin_products_path
    else
      flash[:notice] = 'Something went wrong'
      redirect_to admin_products_path
    end
  end
  

  private

  def set_product
    @product = Product.find(params[:id]) # find(params[:id]) 可以撈到指定的資料
  end

  def product_params # rails 要求的驗證，只要是會寫入資料庫的物件，都需要告知許可的可寫入屬性有哪些
    params.require(:product).permit(:name, :description, :price, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    #session[:abc] = '123'
    @products = Product.page(params[:page]).per(9) # 撈資料，首頁顯示的數量
  end
    
  def show
    @product = Product.find(params[:id]) # find(params[:id]) 可以撈到指定的資料
  end
  
  def add_to_cart
    @product = Product.find(params[:id]) # find(params[:id]) 可以撈到指定的資料
    current_cart.add_cart_item(@product) # current_cart 是自製的helper；add_cart_item() 來自models/cart.rb

    #redirect_back(fallback_location: root_path) #啟用ajax後，就不用轉向
  end

  # 名稱不用 delete ，是因為 delete 專門給 destroy 使用
  def remove_from_cart
    @product = Product.find(params[:id]) # find(params[:id]) 可以撈到指定的資料
    
    cart_item = current_cart.cart_items.find_by(product_id: @product) #撈指定的product，此時用關聯表連結；find_by回傳第一筆資料
    cart_item.destroy # 懶人刪除法，全部刪除

    #redirect_back(fallback_location: root_path) #啟用ajax後，就不用轉向
  end

  def adjust_item
    @product = Product.find(params[:id]) # find(params[:id]) 可以撈到指定的資料
    cart_item = current_cart.cart_items.find_by(product_id: @product) #撈指定的product，此時用關聯表連結；find_by回傳第一筆資料

    # 正確的數量+-
    if params[:type] == "add" # link_to那邊有設定 :symbol，好辨識該連結的特徵
      cart_item.quantity += 1
    elsif params[:type] == "substract" # link_to那邊有設定 :symbol，好辨識該連結的特徵
      cart_item.quantity -= 1
    end

    if cart_item.quantity == 0 #用數量來判定該product該不該移除
      cart_item.destroy
    else
      cart_item.save
    end
    #redirect_back(fallback_location: root_path) #啟用ajax後，就不用轉向
  end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<div class="container">
  <div class="row">
    <h1> <%= action_name.capitalize %> Product</h1>
    <!-- 這樣寫就會自動更換名稱 -->
    <%= render partial: "shared/form_error", locals: { object: @product } %>

    <%= form_for [:admin, @product] do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <p><%= image_tag @product.image, width: '300px', class: "edit-image" %></p>
        <span><%= f.file_field :image %></span>
      </div>
      <div class="form-group">
        <%= f.text_area :description, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.number_field :price, in: 1..999 %>
      </div>
      <div class="form-group edit-submit">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/products/edit.html.erb
<%= render 'form' %>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="switch">
        <ul class="admin-nav">
          <li class="btn btn-default active">
            <%= link_to "Products", admin_products_path %>
          </li>
          <li class="btn btn-default">
            <%= link_to "Orders", admin_orders_path %>
          </li>
          <li class="btn btn-default">
            <%= link_to "Users", admin_users_path %>
          </li>
        </ul>
      </div>
      <br>
      <div>
        <%= link_to  "Add New One", new_admin_product_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>
              Product Name
            </th>
            <th>
              Image
            </th>
            <th>
              Price
            </th>
            <th colspan="2">
              Option
            </th>
          </tr>
        </thead>
        <tbody>
          <% @products.each do |product| %>
          <tr>
            <td><%= product.name %></td>
            <td><%= image_tag product.image, width: '60px' %></td>
            <td><%= product.price %></td>
            <td>
              <%= link_to "Edit Detail", edit_admin_product_path(product) %>
            </td>
            <td>
              <%= link_to "", admin_product_path(product), method: :delete, data: {confirm: "Are you sure?"}, class: "glyphicon glyphicon-trash" %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= paginate @products %>
      </div>

    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<%= render 'form' %>