config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :products, only: [:index, :show] do
    # 自製的連結，因為不符合 RESTful 的七個名稱，所以要標注動詞(post)、使用的路徑名稱、對象是單一(member)還是全部
    post :add_to_cart, on: :member
    post :remove_from_cart, on: :member
    post :adjust_item, on: :member
  end
  root 'products#index'

  resource :cart
  # 因為 cart 上的商品加減都會用到，所以全開

  resources :orders do
    post :checkout_spgateway, on: :member
    # post :spgateway_return, on: :collection
    # 打算繞過 orders，改採下方寫法
  end

  post "spgateway/return" #因此需要專屬的 controller
  post "spgateway/notify"

  namespace :admin do
    resources :products
    resources :users
    resources :orders
    root 'products#index'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>ShoppingCart</title>
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body id="<%= controller_name %>_<%= action_name%>">
  <!-- 導覽列 -->
  <nav class="navbar navbar-default">
    <div class="container-fluid" id="nav">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
          aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">
          <span class="glyphicon glyphicon-knight" aria-hidden="true"></span>
        </a>
        <%= link_to "Shopping!", root_path, class: "navbar-brand"%>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="pull-right text-right nav navbar-nav">
          <% if current_user %>
          <li>
            <%= link_to "Welcome! #{current_user.email}"%>
          </li>
          <% end %>
          <% if current_user&.admin? %>
            <li>
              <%= link_to "Admin", admin_products_path %>
            </li>
          <% end %>
          <li>
            <%= link_to "Cart", cart_path %>
          </li>
          <li>
            <%= link_to  "Order", orders_path %>
          </li>
          <li>
            <% if current_user %>
              <%= link_to("登出", destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to("登入", new_user_session_path) %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <% if flash[:notice] %>
  <div class="container">
    <div class="row">
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    </div>
  </div>
  <% end %>

  <% if flash[:alert] %>
  <div class="container">
    <div class="row">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    </div>
  </div>
  <% end %>
  
  <%= yield %>
</body>

</html>